apiVersion: v1
kind: Service
metadata:
  name: dgraph-zero
spec:
  selector:
    app: dgraph-zero
  ports:
  - name: zero-grpc
    port: 5080
    targetPort: 5080
  - name: zero-http
    port: 6080
    targetPort: 6080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: dgraph-alpha
spec:
  selector:
    app: dgraph-alpha
  ports:
  - name: alpha-http
    port: 8080
    targetPort: 8080
  - name: alpha-grpc
    port: 9080
    targetPort: 9080
  type: ClusterIP 